React Metrics webpage - Full site
angeluray/cp-coinforyou pull request #4
Opened 2022-10-07 21:17 UTC by angeluray

2022-10-07 23:28 UTC, vickymarz requested changes
Hi @angeluray, 

Good job so far! 🤝 
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

- Good video presentation ✔️ 
- Pull request summary is descriptive and detailed ✔️ 
- Good commit messages ✔️ 
- Code is clean and well organized ✔️ 

## Suggested changes
_Check the comments under the review._

- [ ] Kindly ensure that your README contains an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-07 23:28 UTC, vickymarz commented on src/components/cryptohome.js
> +  /* console.log(cryptos); */
- [ ] Kindly remove commented code from your codebase so as to keep your codebase clean and readable 😄

2022-10-07 23:28 UTC, vickymarz commented on src/components/cryptoList.js
> +  /* console.log(cryptos); */
- [ ] Kindly remove commented code from your codebase so as to keep your codebase clean and readable 😄

2022-10-08 04:15 UTC, Rustamxon7 approved these changes
## Hello @angeluray👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

No Linter errors 💯

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-08 04:19 UTC, merged